# Exercise 5A: NumPy Fundamentals

This notebook practices basic NumPy skills, including creating arrays, checking data types,
transposing arrays,indexing values, slicing values, and creating a 3D array

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ["apple", "banana", "cherry", "date"]
print(fruits)

['apple', 'banana', 'cherry', 'date']


In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [6]:
print(arr_1.dtype)

#The dtype checks the type of data inside the array.
#The output <U6 means the array contains text values, and the longest word has 6 characters

<U6


In [7]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [8]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [9]:
print(arr_2)

# No, arr_2.T does not permanently change arr_2
# It only displays arr_2 in a transposed view.

[[10 11 12]
 [13 14 15]]


In [10]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [11]:
arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]
])
print(arr_4)

[5 4]


In [12]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
