# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [3]:
r_1 = np.random.randint(1, 21, size=2)

print(r_1)

[19  5]


In [5]:
r_2 = np.random.randint(1, 21, size=(1, 2))

print(r_2)

[[ 1 12]]


In [6]:
r_3 = np.random.rand(2, 1)

print(r_3)

[[0.23484988]
 [0.72158833]]


In [7]:
r_4 = np.random.randint(20, 101, size=(4, 5))

print(r_4)

[[68 66 90 72 72]
 [55 97 77 28 95]
 [34 86 82 75 95]
 [76 99 35 34 60]]


In [8]:
r_5 = np.random.rand(4, 5)

print(r_5)

[[0.49693011 0.13895608 0.89420529 0.03603812 0.85773917]
 [0.71306019 0.7157942  0.79419651 0.82921639 0.66231757]
 [0.25896086 0.12878135 0.64863113 0.61142932 0.89375275]
 [0.65376675 0.1124324  0.53886819 0.59315984 0.56996127]]


## Generating Random Choices from an Array

In [9]:
students = np.array([
    "Hana", "Nji", "Patrick", "Demy",
    "Malaika", "Jonathan", "Chris", "Leon",
    "Jodan", "Marenza", "Shay Ray", "Ndifon"
])

print(students)

['Hana' 'Nji' 'Patrick' 'Demy' 'Malaika' 'Jonathan' 'Chris' 'Leon' 'Jodan'
 'Marenza' 'Shay Ray' 'Ndifon']


In [12]:
call_on = np.random.choice(students)

print(call_on)

Hana


In [14]:
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)

# This is not the best way to assign breakout groups because the same student can be selected more than once.
# Some students may appear multiple times, while others may not appear at all.

[['Shay Ray' 'Demy' 'Chris' 'Shay Ray']
 ['Malaika' 'Patrick' 'Hana' 'Nji']
 ['Nji' 'Jonathan' 'Malaika' 'Leon']]


In [17]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.00, 0.10, 0.10, 0.05, 0.05, 0.10, 0.05, 0.05, 0.05, 0.10, 0.05]
)

print(call_on_weighted)

# Hana has a 30% chance of being selected.
# Nji has a 0% chance, so Nji will not be selected.
# The other students have smaller probability values.

['Malaika' 'Hana' 'Patrick' 'Jonathan' 'Shay Ray']


## Generating a Normal Distribution

In [18]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)

[[ 6.45346935  7.55970335  8.93499919  4.73544581 13.87591367]
 [22.65423773 -1.36476949 11.00306899 -1.82016211 13.89395641]
 [ 9.92208381 19.18827684 17.10669747  1.78798876  5.60441004]
 [ 7.34791093  6.72244983 13.2246163  10.63777412  7.87034054]]
