# Exercise 1.C Performing Operations on Arrays
## Ndifon Caleb Ndakina | Week 7

This notebook demonstrates NumPy array operations including permutations,
mathematical operations, broadcasting, rounding, cumulative operations,
and teamwork data analysis

In [1]:
import numpy as np

## Sample Arrays

Create sample arrays to use throughout the notebook.

In [2]:
r_1 = np.random.randint(1, 20, size=2)

r_2 = np.random.randint(1, 50, size=(2,2))

r_3 = np.random.uniform(1, 20, size=(2,2))

r_4 = np.random.randint(1, 100, size=(2,5))

r_5 = np.random.choice(
    ["Caleb", "Hana", "Patrick", "Nji", "Chris"],
    size=5
)

print("r_1:\n", r_1)
print("\nr_2:\n", r_2)
print("\nr_3:\n", r_3)
print("\nr_4:\n", r_4)
print("\nr_5:\n", r_5)

r_1:
 [8 1]

r_2:
 [[27 41]
 [40 28]]

r_3:
 [[11.47138235 14.21056174]
 [15.33944272 11.54458686]]

r_4:
 [[43 44 75 14 54]
 [23 82 98 67 52]]

r_5:
 ['Caleb' 'Caleb' 'Caleb' 'Chris' 'Patrick']


## Permutations

This section demonstrates shuffle and permutation operations.

In [3]:
print("Original r_4:")
print(r_4)

Original r_4:
[[43 44 75 14 54]
 [23 82 98 67 52]]


In [4]:
np.random.shuffle(r_4)

print("Shuffled r_4:")
print(r_4)

Shuffled r_4:
[[43 44 75 14 54]
 [23 82 98 67 52]]


The shuffle function changes the original array directly by rearranging the rows.
The values are mixed in a random order.

In [5]:
new_shuffle = np.random.permutation(r_4)

print("Permutation Result:")
print(new_shuffle)

print("\nOriginal r_4:")
print(r_4)

Permutation Result:
[[43 44 75 14 54]
 [23 82 98 67 52]]

Original r_4:
[[43 44 75 14 54]
 [23 82 98 67 52]]


Shuffle changes the original array itself, while permutation creates a new shuffled copy.
Use shuffle when you want to permanently rearrange data.
Use permutation when you want to keep the original array unchanged.

## Mathematical Operations

This section demonstrates array addition and broadcasting.

In [6]:
print("r_1:")
print(r_1)
print("Shape:", r_1.shape)

print("\nr_2:")
print(r_2)
print("Shape:", r_2.shape)

print("\nAddition:")
print(np.add(r_1, r_2))

r_1:
[8 1]
Shape: (2,)

r_2:
[[27 41]
 [40 28]]
Shape: (2, 2)

Addition:
[[35 42]
 [48 29]]


In [7]:
print("r_1:")
print(r_1)

print("\nr_3:")
print(r_3)

print("\nAddition:")
print(np.add(r_1, r_3))

r_1:
[8 1]

r_3:
[[11.47138235 14.21056174]
 [15.33944272 11.54458686]]

Addition:
[[19.47138235 15.21056174]
 [23.33944272 12.54458686]]


In [11]:
print("r_2:")
print(r_2)

print("\nr_4:")
print(r_4)

# This may produce a print(np.add(np.array([1,1,1,1,1]), r_4))broadcasting error
# because the shapes are different

r_2:
[[27 41]
 [40 28]]

r_4:
[[43 44 75 14 54]
 [23 82 98 67 52]]


In [9]:
print(np.add(np.array([1]), r_4))

[[44 45 76 15 55]
 [24 83 99 68 53]]


In [10]:
print(np.add(np.array([[1]]), r_4))

[[44 45 76 15 55]
 [24 83 99 68 53]]


In [12]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[44 45 76 15 55]
 [24 83 99 68 53]]


# This produces a broadcasting error
# because shapes are incompatible

# np.add(np.array([[1],[1]]), r_4)

Broadcasting allows NumPy to perform operations on arrays with different shapes.
NumPy stretches smaller arrays to match larger arrays when possible.
The resulting shape depends on the compatible dimensions of both arrays.

## Rounding

This section demonstrates different rounding methods.

In [15]:
print(r_3)

[[11.47138235 14.21056174]
 [15.33944272 11.54458686]]


In [16]:
print(np.trunc(r_3))

[[11. 14.]
 [15. 11.]]


In [18]:
print(np.fix(r_3))

[[11. 14.]
 [15. 11.]]


In [19]:
print(np.floor(r_3))

[[11. 14.]
 [15. 11.]]


In [21]:
print(np.ceil(r_3))

[[12. 15.]
 [16. 12.]]


In [22]:
print(np.round(r_3, 2))

[[11.47 14.21]
 [15.34 11.54]]


## Cumulative Operations

This section demonstrates sums and cumulative totals.

In [23]:
print(r_4)

[[43 44 75 14 54]
 [23 82 98 67 52]]


In [24]:
print("Total Sum:")
print(np.sum(r_4))

Total Sum:
552


In [25]:

print("Axis 0 Sum:")
print(np.sum(r_4, axis=0))

Axis 0 Sum:
[ 66 126 173  81 106]


In [26]:
print("Axis 1 Sum:")
print(np.sum(r_4, axis=1))

Axis 1 Sum:
[230 322]


In [27]:
print("Cumulative Sum:")
print(np.cumsum(r_4))

Cumulative Sum:
[ 43  87 162 176 230 253 335 433 500 552]


In [28]:
print("Cumulative Sum Axis 0:")
print(np.cumsum(r_4, axis=0))

Cumulative Sum Axis 0:
[[ 43  44  75  14  54]
 [ 66 126 173  81 106]]


## Grocery Problem

This section analyzes grocery bag contents using arrays.

In [29]:
bag1 = np.array([2, 3, 4, 0])

bag2 = np.array([4, 0, 1, 2])

print("Bag 1:", bag1)
print("Bag 2:", bag2)

Bag 1: [2 3 4 0]
Bag 2: [4 0 1 2]


In [30]:
print(f"The first bag contains {np.sum(bag1)} items.")
print(f"The second bag contains {np.sum(bag2)} items.")

The first bag contains 9 items.
The second bag contains 7 items.


In [31]:
totals = bag1 + bag2

print(f"""
There are {totals[0]} vegetables,
{totals[1]} fruits,
{totals[2]} boxes of snacks,
and {totals[3]} beverages.
""")


There are 6 vegetables,
3 fruits,
5 boxes of snacks,
and 2 beverages.



## Teamwork

This section tracks door-knocking activity for a voter registration campaign.

In [32]:
ali = np.array([5, 4, 6, 4, 2])

ben = np.array([0, 5, 5, 3, 4])

carla = np.array([3, 6, 0, 3, 4])

print("Ali:", ali)
print("Ben:", ben)
print("Carla:", carla)

Ali: [5 4 6 4 2]
Ben: [0 5 5 3 4]
Carla: [3 6 0 3 4]


In [33]:
all_knocks = np.array([ali, ben, carla])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [35]:
person_totals = np.sum(all_knocks, axis=1)

group_total = np.sum(all_knocks)

print("Total doors knocked by each person:")
print(person_totals)

print("\nGroup Total:")
print(group_total)

Total doors knocked by each person:
[21 17 16]

Group Total:
54


In [39]:
daily_totals = np.sum(all_knocks, axis=0)

rolling_total = np.cumsum(daily_totals)

estimated_votes = rolling_total * 0.5

print("Estimated Rolling Votes:")
print(estimated_votes)

Estimated Rolling Votes:
[ 4.  11.5 17.  22.  27. ]
